name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Set up ENV and Tools
      run: |
        mkdir -p ~/go/bin
        export GOPATH=~/go
        export GOBIN=$GOPATH/bin
        export PATH=$PATH:$GOBIN
        export GO111MODULE=on
        go get -u golang.org/x/tools/...  
        go get -u github.com/golangci/golangci-lint/...

    - name: Show env
      run: env

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: make all
    
