name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    
    - name: Set up Zookeeper
      run: |
        mkdir ~/zk
        cd ~/zk
        curl -O https://us.mirrors.quenda.co/apache/zookeeper/current/apache-zookeeper-3.6.0-bin.tar.gz
        tar -xf apache-zookeeper-3.6.0-bin.tar.gz
        cd apache-zookeeper-3.6.0-bin
        cp conf/zoo_sample.cfg conf/zoo.cfg
        bin/zkServer.sh start

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    
    - name: Build
      run: |
        mkdir -p ~/go/bin
        export GOPATH=~/go
        export GOBIN=$GOPATH/bin
        export PATH=$PATH:$GOBIN
        export GO111MODULE=on
        env
        go get -u golang.org/x/tools/...  
        go get -u github.com/golangci/golangci-lint/...
        make all
    
